[package]
name = "zemse-helios-verifiable-api-client"
version.workspace = true
edition = "2021"
license = "MIT"
description = "Client for the Helios Verifiable API, providing utilities to interact with the API endpoints"

[dependencies]
alloy.workspace = true
eyre.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
reqwest-retry.workspace = true
reqwest-middleware.workspace = true
async-trait.workspace = true
tokio.workspace = true
url.workspace = true

# self crates
helios-verifiable-api-types = { package = "zemse-helios-verifiable-api-types", path = "../types", version = "0.9.0" }
helios-common = { package = "zemse-helios-common", path = "../../common", version = "0.9.0" }
